# Generated by Django 5.2.7 on 2025-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book entries'), ('can_create', 'Can create a new book entry'), ('can_edit', 'Can edit existing book entries'), ('can_delete', 'Can delete book entries')]},
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2000),
        ),
    ]
