# notifications/urls.py (FINAL FIXED VERSION for NotificationViewSet)

from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import NotificationViewSet

# Create a router instance
router = DefaultRouter()

# Register the NotificationViewSet with the router
# The base name 'notification' is used to generate URL names (e.g., 'notification-list')
router.register(r'', NotificationViewSet, basename='notification')

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]