# Generated by Django 5.2.7 on 2025-11-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book entry'), ('can_change_book', 'Can edit existing book entries'), ('can_delete_book', 'Can delete book entries')]},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Librarian', 'Librarian'), ('Member', 'Member'), ('Guest', 'Guest')], default='Member', max_length=10),
        ),
    ]
