# Generated by Django 5.2.8 on 2025-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book entries'), ('can_create', 'Can create a new book entry'), ('can_edit', 'Can edit existing book entries'), ('can_delete', 'Can delete book entries')]},
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Librarian', 'Librarian'), ('Member', 'Member'), ('Guest', 'Guest')], default='Member', max_length=10),
        ),
    ]
