# Generated by Django 5.2.7 on 2025-12-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
    ]
