# Generated by Django 5.2.7 on 2025-11-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the author.', max_length=200, verbose_name='Author Name')),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The official title of the book.', max_length=255, verbose_name='Book Title')),
                ('publication_year', models.IntegerField(help_text='The year the book was published (e.g., 2024).', verbose_name='Publication Year')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author', verbose_name='Author')),
            ],
            options={
                'ordering': ['publication_year', 'title'],
            },
        ),
    ]
