# Generated by Django 5.2.7 on 2025-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=250)),
                ('author', models.CharField(help_text='Author of the book', max_length=250)),
            ],
        ),
    ]
