# accounts/urls.py (CLEAN AND CONSOLIDATED)

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserRegistrationView, 
    UserLoginView, 
    UserProfileView,
    UserViewSet # <-- The ViewSet with the follow action
)

# 1. Router for User Listing/Detail/Follow/Unfollow
# The base path for this router will be /api/users/
router = DefaultRouter()
router.register(r'users', UserViewSet, basename='user')

urlpatterns = [
    # 2. Include the routes generated by the router (e.g., /api/users/, /api/users/2/follow/)
    path('', include(router.urls)), 
    
    # 3. Include your original, separate views for Auth and Profile
    path('register/', UserRegistrationView.as_view(), name='user-register'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
]